Add build target: debian bookworm
wkhtmltopdf/packaging pull request #150
Opened 2023-04-10 12:02 UTC by piotrpawlaczek

Add build target debian bookworm. 

The official wkhtmltopdf package does not have the QT patch and Debian bookworm RC is currently in "hard freeze" mode, as stated in this announcement: https://lists.debian.org/debian-devel-announce/2023/03/msg00004.html.

2023-04-11 01:19 UTC, ashkulz requested changes
Also, I'd appreciate if you would create a configuration for Raspberry Pi (`raspberrypi.bookworm-armhf`) -- you can probably copy/paste the configuration with a few changes, it'd done similarly for `bullseye` :+1:

2023-04-11 01:19 UTC, ashkulz commented on build.yml
> +      libssl1.1
This looks wrong, as [`libssl-dev` depends on libssl3](https://packages.debian.org/bookworm/libssl-dev).

2023-04-11 01:19 UTC, ashkulz commented on .azure-pipelines.yml
> +        target: bookworm-amd64
Please revert these changes, as Azure Pipelines is no longer used.

2023-04-11 01:19 UTC, ashkulz commented on build.yml
> +    matrix: ['amd64', 'arm64']
Can you keep it the same as `bullseye` i.e
```suggestion
    matrix: ['amd64', 'i386', 'arm64', 'armhf', 'armel', 'ppc64el']
```
assuming that docker images are available for all the above architectures?

2023-04-11 08:45 UTC, ashkulz approved these changes

2023-04-11 08:46 UTC, merged

2023-04-11 10:47 UTC, piotrpawlaczek commented
@ashkulz Thx, would it be possible to publish the bookworm .deb packages here?

2023-04-12 01:11 UTC, ashkulz commented
Like [I said on the ticket](https://github.com/wkhtmltopdf/packaging/issues/149#issuecomment-1501713022), it doesn't make sense to publish packages as there's no official release yet.

2023-05-22 03:48 UTC, ashkulz commented
@piotrpawlaczek published a [new release 0.12.6.1-3](https://github.com/wkhtmltopdf/packaging/releases/tag/0.12.6.1-3), some builds are still ongoing due to hitting the 6-hour cutoff.